"""Curated starter question bank used to enrich the local MVP database."""

QUESTION_BANK = {
    "Python": [
        ("How does Python manage memory and garbage collection?", "Runtime", "Advanced"),
        ("When would you use a set instead of a list?", "Data Structures", "Basic"),
        ("How do context managers work and how would you write one?", "Language Features", "Advanced"),
        ("What is the purpose of type hints in a Python codebase?", "Typing", "Intermediate"),
        ("How would you test a Flask endpoint?", "Testing", "Intermediate"),
        ("What causes a circular import and how can you prevent it?", "Modules", "Advanced"),
        ("How do you safely manage secrets in a Python deployment?", "Production", "Intermediate"),
        ("What is the difference between threading and multiprocessing in Python?", "Concurrency", "Advanced"),
        ("How would you design a reusable Python package?", "Architecture", "Intermediate"),
        ("How do you profile and improve a slow database-backed Python service?", "Performance", "Advanced"),
    ],
    "Data Science": [
        ("How do you handle missing values in a dataset?", "Data Cleaning", "Basic"),
        ("Explain the difference between classification and regression.", "Machine Learning", "Basic"),
        ("What is cross-validation and why is it useful?", "Model Evaluation", "Intermediate"),
        ("How do precision and recall trade off?", "Metrics", "Intermediate"),
        ("What is feature leakage and how do you detect it?", "Features", "Advanced"),
        ("When would you standardize or normalize features?", "Preprocessing", "Intermediate"),
        ("Explain overfitting and two ways to reduce it.", "Model Quality", "Basic"),
        ("How would you explain a model prediction to a non-technical stakeholder?", "Communication", "Intermediate"),
        ("What is the purpose of a baseline model?", "Modeling", "Basic"),
        ("How would you monitor a machine learning model after deployment?", "MLOps", "Advanced"),
    ],
    "Data Analytics": [
        ("How do you choose the right chart for a business question?", "Visualization", "Basic"),
        ("What is the difference between a metric and a dimension?", "Analytics", "Basic"),
        ("How would you investigate a sudden drop in conversion rate?", "Investigation", "Intermediate"),
        ("Explain a window function use case in SQL.", "SQL", "Advanced"),
        ("How do you validate a dashboard before sharing it?", "Quality", "Intermediate"),
        ("What is cohort analysis and when is it useful?", "Business Analysis", "Intermediate"),
        ("How do you deal with duplicate events in an analytics pipeline?", "Data Quality", "Advanced"),
        ("What makes a KPI actionable?", "KPIs", "Basic"),
        ("How would you present an ambiguous analysis to leadership?", "Communication", "Intermediate"),
        ("Describe a data project where you changed your approach after finding new evidence.", "Behavioral", "Intermediate"),
    ],
    "Web Development": [
        ("What happens in a browser after a user enters a URL?", "Web Basics", "Basic"),
        ("Explain the difference between cookies, local storage and session storage.", "Browser", "Intermediate"),
        ("How would you make a web page accessible?", "Accessibility", "Intermediate"),
        ("What is responsive design and how do you test it?", "Frontend", "Basic"),
        ("How do HTTP status codes help diagnose an API problem?", "HTTP", "Basic"),
        ("What is CORS and why does it exist?", "Security", "Intermediate"),
        ("How would you protect a form from cross-site request forgery?", "Security", "Advanced"),
        ("What are the benefits of server-side rendering?", "Architecture", "Intermediate"),
        ("How do you reduce layout shift and improve page performance?", "Performance", "Advanced"),
        ("How would you organize CSS for a growing product?", "CSS", "Intermediate"),
    ],
    "Full Stack Python": [
        ("How would you structure a Flask application with blueprints?", "Flask", "Intermediate"),
        ("What belongs in a service layer?", "Architecture", "Intermediate"),
        ("How do you validate and serialize API input?", "APIs", "Intermediate"),
        ("How would you paginate a large database query?", "Databases", "Intermediate"),
        ("What is a database transaction and when should it be used?", "Databases", "Basic"),
        ("How do you handle background work in a web application?", "Backend", "Advanced"),
        ("What logs and metrics would you add to a production API?", "Operations", "Intermediate"),
        ("How would you secure an authenticated REST API?", "Security", "Advanced"),
        ("How do you prevent N+1 query problems?", "ORM", "Advanced"),
        ("Describe how you would deploy a Python web application.", "Deployment", "Intermediate"),
    ],
    "Java": [
        ("Explain the Java memory model at a high level.", "Runtime", "Advanced"),
        ("When would you choose an ArrayList over a LinkedList?", "Collections", "Basic"),
        ("What is dependency injection in Java?", "Architecture", "Intermediate"),
        ("How do checked and unchecked exceptions differ?", "Exceptions", "Intermediate"),
        ("What problem do Java streams solve?", "Functional Java", "Basic"),
        ("Explain immutability and why it helps concurrent programs.", "Design", "Intermediate"),
        ("How would you troubleshoot a memory leak in a Java service?", "Operations", "Advanced"),
        ("What is the purpose of an interface default method?", "Language Features", "Intermediate"),
        ("How do you test code that calls an external service?", "Testing", "Intermediate"),
        ("What makes a class thread-safe?", "Concurrency", "Advanced"),
    ],
    "C++": [
        ("Explain RAII and why it matters in C++.", "Memory", "Intermediate"),
        ("What is the rule of five?", "Objects", "Advanced"),
        ("How do smart pointers improve ownership management?", "Memory", "Intermediate"),
        ("What is template specialization?", "Templates", "Advanced"),
        ("When should you use a reference instead of a pointer?", "Language Basics", "Basic"),
        ("Explain move semantics with a practical example.", "Performance", "Advanced"),
        ("How does const correctness improve an API?", "Design", "Intermediate"),
        ("What is the difference between compile-time and runtime polymorphism?", "Polymorphism", "Intermediate"),
        ("How would you diagnose undefined behavior?", "Debugging", "Advanced"),
        ("What are the tradeoffs of a header-only library?", "Build Systems", "Intermediate"),
    ],
    "C Programming": [
        ("What is pointer arithmetic and where is it safe?", "Pointers", "Intermediate"),
        ("How does a C string differ from a character array?", "Strings", "Basic"),
        ("What is a dangling pointer?", "Memory", "Basic"),
        ("Explain the purpose of the static keyword in C.", "Storage", "Intermediate"),
        ("What is a function pointer used for?", "Functions", "Advanced"),
        ("How do header guards prevent build problems?", "Build", "Basic"),
        ("What is undefined behavior in C?", "Safety", "Intermediate"),
        ("How would you find a buffer overflow?", "Debugging", "Advanced"),
        ("Explain the difference between a macro and an inline function.", "Preprocessor", "Intermediate"),
        ("How do you design a C API that owns allocated memory clearly?", "API Design", "Advanced"),
    ],
    "SQL": [
        ("How would you find the second highest salary in a table?", "Queries", "Intermediate"),
        ("What is a correlated subquery?", "Queries", "Advanced"),
        ("Explain ACID properties with a business example.", "Transactions", "Intermediate"),
        ("When can an index make a query slower?", "Performance", "Advanced"),
        ("How do you identify duplicate rows?", "Data Quality", "Basic"),
        ("What is a common table expression?", "Queries", "Intermediate"),
        ("How would you model a many-to-many relationship?", "Schema Design", "Basic"),
        ("What does an execution plan tell you?", "Performance", "Advanced"),
        ("Explain a safe database migration strategy.", "Operations", "Intermediate"),
        ("What is the difference between DELETE, TRUNCATE and DROP?", "SQL Basics", "Basic"),
    ],
    "AutoCAD": [
        ("How do blocks improve drafting productivity?", "Drafting", "Basic"),
        ("What is the purpose of xrefs in a project?", "Collaboration", "Intermediate"),
        ("How do you maintain drawing standards across a team?", "Standards", "Intermediate"),
        ("Explain annotation scale and when it causes problems.", "Annotation", "Advanced"),
        ("How would you prepare a drawing for plotting?", "Output", "Basic"),
        ("What is the difference between a polyline and separate lines?", "Geometry", "Basic"),
        ("How do you audit and repair a corrupted drawing?", "Quality", "Advanced"),
        ("What are dynamic blocks useful for?", "Blocks", "Intermediate"),
        ("How do you use coordinates accurately in AutoCAD?", "Geometry", "Basic"),
        ("How would you organize layers for a multi-discipline drawing?", "Layers", "Intermediate"),
    ],
    "SolidWorks": [
            ("Explain the difference between a part, assembly and drawing.", "CAD Basics", "Basic"),
            ("What are sketch in SolidWorks?", "Assembly", "Intermediate"),
            ("What is the difference between Fully Defined and Under Defined Sketches?", "Assembly", "Intermediate"),
            ("What are Geometric relations in a sketch?", "Assembly", "Intermediate"),
            ("What is the Extruded Boss/base?", "Part Design", "Intermediate"),
            ("What is the diference between Fillet and Chamfer?", "Assembly", "Intermediate"),
            ("What is the purpose of shell feature?", "Assembly", "Intermediate"),
            ("What is the revolve feature used for?", "Assembly", "Intermediate"),
            ("What is Assembly in SolidWorks?", "Assembly", "Intermediate"),
            ("What ais Mate?", "Assembly", "Intermediate"),
            ("What is Exploded view?", "Assembly", "Intermediate"),
            ("What is a Solid Work Drawing?", "Drafting", "Intermediate"),
            ("What is purpose of section view?", "Assembly", "Intermediate"),
            ("What is the difference between Coincident and center Mate?", "Assembly", "Intermediate"),
            ("What is the difference between Solid Modeling and Surface Modeling, and what is a Flat Pattern in sheet metal?", "Surfacing and sheet metal", "Intermediate"),
            ("Explain the purpose of design intent.", "Part Design", "Advanced"),
        ],

    "CATIA": [
        ("What is the role of a PartBody in CATIA?", "Part Design", "Basic"),
        ("How do constraints control a CATIA sketch?", "Sketcher", "Basic"),
        ("When would you use Generative Shape Design?", "Surface Design", "Intermediate"),
        ("How do you build a stable assembly structure?", "Assembly", "Intermediate"),
        ("What is a hybrid body?", "Modeling", "Advanced"),
        ("How would you diagnose an update error?", "Debugging", "Intermediate"),
        ("What is the purpose of publications in an assembly?", "Assembly", "Advanced"),
        ("How do you create reusable power copies?", "Automation", "Advanced"),
        ("What checks are important before releasing a CATIA model?", "Quality", "Basic"),
        ("How do you keep design intent clear for another engineer?", "Design Intent", "Intermediate"),
    ],
    "Product Designing": [
        ("How do you turn a customer need into a design requirement?", "Requirements", "Basic"),
        ("What is design for manufacturability?", "Manufacturing", "Basic"),
        ("How do you compare competing concepts?", "Concept Design", "Intermediate"),
        ("What is tolerance stack-up analysis?", "Engineering", "Advanced"),
        ("How do material choices affect product design?", "Materials", "Intermediate"),
        ("Explain the difference between verification and validation.", "Quality", "Basic"),
        ("How would you run a design review?", "Collaboration", "Intermediate"),
        ("What is a minimum viable prototype?", "Prototyping", "Basic"),
        ("How do cost and reliability influence a design decision?", "Tradeoffs", "Advanced"),
        ("Describe a product improvement you would make and how you would measure it.", "Innovation", "Intermediate"),
    ],
    "Ansys": [
        ("What is mesh convergence?", "Meshing", "Intermediate"),
        ("How do boundary conditions affect an FEA result?", "Simulation", "Basic"),
        ("What is the difference between linear and nonlinear analysis?", "Analysis", "Intermediate"),
        ("How do you judge whether a simulation result is realistic?", "Validation", "Advanced"),
        ("What is a contact definition in structural analysis?", "Contacts", "Intermediate"),
        ("How does element quality affect accuracy?", "Meshing", "Advanced"),
        ("When would you use a transient simulation?", "Dynamics", "Intermediate"),
        ("How do you document simulation assumptions?", "Reporting", "Basic"),
        ("What is factor of safety and how is it interpreted?", "Results", "Basic"),
        ("How would you reduce solve time without compromising confidence?", "Performance", "Advanced"),
    ],
    "Revit Architecture": [
        ("What is BIM and how does Revit support it?", "BIM", "Basic"),
        ("How do families differ from types and instances?", "Families", "Basic"),
        ("How would you coordinate architectural and structural models?", "Coordination", "Intermediate"),
        ("What are worksets used for?", "Collaboration", "Intermediate"),
        ("How do view templates improve consistency?", "Documentation", "Basic"),
        ("What is a shared parameter?", "Data", "Intermediate"),
        ("How do you manage design options?", "Design", "Advanced"),
        ("What checks do you perform before issuing drawings?", "Quality", "Basic"),
        ("How would you resolve a model warning?", "Debugging", "Intermediate"),
        ("How do schedules help a project team?", "Documentation", "Intermediate"),
    ],
    "SketchUp": [
        ("How do groups and components differ in SketchUp?", "Modeling", "Basic"),
        ("How do you keep a large model performant?", "Performance", "Intermediate"),
        ("What is the benefit of using scenes?", "Presentation", "Basic"),
        ("How do you create accurate geometry?", "Modeling", "Basic"),
        ("When would you use section planes?", "Documentation", "Basic"),
        ("How do materials and textures affect a presentation model?", "Visualization", "Intermediate"),
        ("How do you organize tags in a shared model?", "Organization", "Intermediate"),
        ("What is a good workflow from concept to presentation?", "Workflow", "Intermediate"),
        ("How would you clean up an imported CAD file?", "Cleanup", "Advanced"),
        ("How do you communicate scale and context in a 3D view?", "Presentation", "Intermediate"),
    ],
    "Generative AI": [
        ("What is the difference between a prompt and a system instruction?", "Prompting", "Basic"),
        ("How would you evaluate an AI-generated answer?", "Evaluation", "Intermediate"),
        ("What is retrieval-augmented generation?", "Architecture", "Intermediate"),
        ("How can prompt injection affect an application?", "Security", "Advanced"),
        ("What is a hallucination and how can you reduce its impact?", "Reliability", "Basic"),
        ("How would you protect sensitive data sent to a model?", "Privacy", "Advanced"),
        ("When should a team use a smaller model?", "Model Selection", "Intermediate"),
        ("How do you design a human review step for AI output?", "Workflow", "Intermediate"),
        ("What makes an evaluation dataset useful?", "Testing", "Advanced"),
        ("Describe a practical AI feature you would prototype for a recruiter.", "Product Thinking", "Intermediate"),
    ],
}
